name: home_recipe_front
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

 
 # 외부 라이브러리
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  shared_preferences: ^2.2.2
  video_player: ^2.8.2
  image_picker: ^1.0.7
  flutter_secure_storage: ^10.0.0
  url_launcher: ^6.2.1
  web: ^1.0.0
  app_links: ^6.3.3
  change_app_package_name: ^1.5.0
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/front/
    - assets/profiles/
    - assets/videos/
    - assets/logos/

  fonts:
    - family: NanumGothicCoding-Regular
      fonts:
        - asset: assets/fonts/NanumGothicCoding-Regular.ttf